---
deployment:
  tasks:
    - export DEPLOYPATH=/home/archeguf/public_html/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp /home/archeguf/repositories/personalWebsite/index.html $DEPLOYPATH
    - /bin/cp /home/archeguf/repositories/personalWebsite/styles.css $DEPLOYPATH
    - /bin/cp /home/archeguf/repositories/personalWebsite/portfolio.html $DEPLOYPATH
    - /bin/cp /home/archeguf/repositories/personalWebsite/other.html $DEPLOYPATH
    - export DEPLOYPATHDE=/home/archeguf/de.archerfsmith.com/
    - /bin/rm -Rf $DEPLOYPATHDE
    - /bin/mkdir $DEPLOYPATHDE
    - /bin/cp /home/archeguf/repositories/personalWebsite//de/index.html $DEPLOYPATHDE
    - /bin/cp /home/archeguf/repositories/personalWebsite//de/styles.css $DEPLOYPATHDE
    - /bin/cp /home/archeguf/repositories/personalWebsite//de/portfolio.html $DEPLOYPATHDE
    - /bin/cp /home/archeguf/repositories/personalWebsite//de/other.html $DEPLOYPATHDE
